import { Problem, ProjectState, Contribution, ResearchGrowth } from './PresentationContent.jsx';
import { useState } from 'react';
import { IrohDetails } from './IrohDetails.jsx';
import { PresentationJourney, Ecosystem } from './Ecosystem.jsx';
import { StandardApps, AppComposition, ImplementationDetails } from './TechnicalDetails.jsx';
import { ArrowRight, ArrowUpRight, ChatCircle, FileText, CheckSquare, CalendarBlank, Folder, Phone, Users, MagnifyingGlass, DotsThree, PaperPlaneTilt, AndroidLogo, AppleLogo, WindowsLogo, Globe, Stack, DeviceMobile, Desktop, Laptop, LockKey, GitBranch, GithubLogo, CaretDown, Check, List, X, Database, Plugs, Code, ShieldCheck, Buildings, Briefcase, CalendarCheck } from '@phosphor-icons/react';
import '@fontsource/manrope/400.css';
import '@fontsource/manrope/500.css';
import '@fontsource/manrope/600.css';
import '@fontsource/manrope/700.css';
const repo='https://github.com/pomazanbohdan/vida';
const navigation=[['problem','Проблема'],['features','Користь'],['demo','Демо'],['architecture','Архітектура'],['project-state','Стан'],['join','Участь']];
const demoTabs=[['Чат',ChatCircle],['Знання',FileText],['Проєкт',CheckSquare]];
const features=[
 {icon:ChatCircle,title:'Спілкування',text:'Від швидкої розмови до рішення, яке легко знайти.',items:['Особисті й групові чати','Форуми з темами обговорень','Файли, голосові повідомлення, реакції','Аудіо- та відеодзвінки до 8 учасників']},
 {icon:FileText,title:'Знання',text:'Ідеї, документи та контекст, що залишаються поруч.',items:['Особисті та спільні нотатки','Форматування, вкладення й зворотні посилання','Спільне редагування та історія змін','Курсори учасників у відкритій нотатці']},
 {icon:CheckSquare,title:'Проєкти',text:'Робота в одному контексті з людьми й матеріалами.',items:['Задачі, підзадачі, виконавці та строки','Списки й дошки зі статусами','Зв’язки із чатами, нотатками та файлами','Особисті проєкти й командні простори']},
 {icon:CalendarBlank,title:'Щоденні інструменти',text:'Спільна основа для всіх ваших просторів.',items:['Контакти та імпорт за вашим вибором','Календар, нагадування й запрошення','Файли з версіями та власними правами','Локальний пошук у вибраному просторі']}
];
const applications=[
 {icon:CheckSquare,title:'Проєкти',status:'Заплановано',text:'Особисті справи й командна робота в одному контексті.',tags:['Задачі та дошки','Нотатки й файли','Чати та форуми']},
 {icon:Briefcase,title:'CRM',status:'Заплановано',text:'Робочий простір для взаємодії бізнесу з клієнтами.',tags:['Клієнти','Комунікація','Пов’язані задачі']},
 {icon:Buildings,title:'Управління ОСББ',status:'Заплановано',text:'Спільний простір будинку для мешканців і команди управління.',tags:['Заявки й виконавці','Погодження','Повідомлення та форум']},
 {icon:CalendarCheck,title:'Запис до бізнесу',status:'Заплановано',text:'Застосунок запису на прийом і взаємодії з локальними сервісами.',tags:['Послуги','Запис на прийом','Зв’язок із бізнесом']}
];
const layers=[
 {title:'Інтерфейс',label:'Flutter',icon:DeviceMobile,text:'Android, iOS, Windows та статичний Web — клієнти зі спільною продуктовою логікою. Кожен адаптується до свого пристрою.'},
 {title:'Спільне ядро',label:'Rust',icon:Code,text:'vida-core визначає правила продукту. vida-runtime відповідає за інфраструктуру, а SDK з’єднує ядро з інтерфейсами.'},
 {title:'Дані та зв’язок',label:'Local-first + Iroh',icon:Database,text:'Локальне збереження та синхронізація між пристроями. Цільова модель — пряме з’єднання, із зашифрованим relay як резервним шляхом.'},
 {title:'Розширення',label:'App packages',icon:Plugs,text:'Пакети поєднують схеми, команди та інтерфейси в конкретному Space. Розширення використовують спільні правила доступу та синхронізації.'}
];
function WorkspaceDemo(){
 const [step,setStep]=useState(0); const [tab,setTab]=useState('Чат'),[draft,setDraft]=useState(''),[messages,setMessages]=useState([]),[done,setDone]=useState(false);
 return <><div className="demo-guide"><p aria-live="polite"><span className="demo-step">Крок {step+1} із 3 · Концепт</span>{['Оберіть повідомлення й збережіть рішення в нотатку.','Нотатка зберігає джерело. Створіть із неї задачу.','Позначте задачу виконаною. Поверніться до нотатки, щоб побачити контекст.'][step]}</p><button onClick={()=>{setStep(0);setTab('Чат');setDone(false);setMessages([]);setDraft('')}}>Перезапустити</button></div><div className="demo-shell"><aside className="demo-sidebar"><span className="demo-brand">VIDA</span><div className="demo-tabs" aria-label="Приклад інтерфейсу">{demoTabs.map(([title,Icon])=><button key={title} onClick={()=>{setTab(title);setStep(demoTabs.findIndex(([t])=>t===title))}} aria-pressed={tab===title} className={tab===title?'active':''}><Icon size={21}/><span>{title}</span></button>)}</div><div className="demo-static">{[[CalendarBlank,'Календар'],[Folder,'Файли'],[Phone,'Дзвінки'],[Users,'Контакти']].map(([Icon,t])=><span key={t}><Icon size={20}/>{t}</span>)}</div><div className="space-label">Команда VIDA <CaretDown size={12}/></div><div className="channels"><span className="selected"># &nbsp; Загальне</span><span># &nbsp; Ідеї</span><span># &nbsp; Проєкт</span><span># &nbsp; Дизайн</span></div></aside><div className="demo-main"><div className="demo-heading"><Users size={27}/><div><strong>Команда VIDA</strong><small>Приклад спільного простору</small></div><MagnifyingGlass className="demo-heading-extra" size={20}/><DotsThree className="demo-heading-extra" size={25}/></div>
 {tab==='Чат'?<><div className="messages"><div className="message"><span className="avatar">О</span><div><div className="author">Олена <time>10:24</time></div><p className="bubble">Зібрала ідеї для нашої зустрічі.</p><button className="resource" onClick={()=>{setTab('Знання');setStep(1)}}><FileText size={22}/><div><strong>Зберегти рішення в нотатку</strong><ul><li>Обговорити концепцію</li><li>Зібрати приклади</li><li>Визначити наступні кроки</li></ul></div></button><button className="resource task" onClick={()=>{setTab('Проєкт');setStep(2)}}><CheckSquare size={23}/><div><strong>Підготувати план</strong><small>Проєкт · 3 коментарі</small></div><span className="tag">{done?'Готово':'В роботі'}</span></button></div></div><div className="message second"><span className="avatar graphite">А</span><div><div className="author">Андрій <time>11:16</time></div><p className="bubble">Чудово! Додам свої нотатки<br/>та пропозиції.</p></div></div>{messages.map((m,i)=><p className="own-message" key={i}>{m}</p>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();if(draft.trim()){setMessages([...messages,draft.trim()]);setDraft('')}}}><ChatCircle size={20}/><input aria-label="Повідомлення в демонстрації" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Спробуйте написати…" maxLength={180}/><button aria-label="Додати повідомлення в демо"><PaperPlaneTilt size={22}/></button></form></>:tab==='Знання'?<div className="demo-document"><span className="eyebrow">ЗНАННЯ · ПРИКЛАД</span><h3>Ідеї команди</h3><p>Один простір для розмов, знань і спільних планів.</p><h4>Наступна зустріч</h4><ul><li>Обговорити концепцію VIDA</li><li>Зібрати приклади щоденних задач</li><li>Визначити наступні кроки</li></ul><button className="resource" onClick={()=>{setTab('Проєкт');setStep(2)}}><CheckSquare size={22}/>Створити задачу з нотатки <ArrowUpRight/></button><p className="demo-note">Джерело: розмова команди. Це концепт, дані існують лише на сторінці.</p></div>:<div className="demo-document"><span className="eyebrow">ПРОЄКТ · ПРИКЛАД</span><h3>Підготувати план</h3><span className="tag">{done?'Готово':'В роботі'}</span><p>Зібрати ідеї команди та перетворити їх на зрозумілі наступні кроки.</p><label className="check-task"><input type="checkbox" checked={done} onChange={e=>setDone(e.target.checked)}/> Узгодити план із командою</label><button className="resource" onClick={()=>{setTab('Знання');setStep(1)}}><FileText size={22}/>Ідеї команди <ArrowUpRight/></button><p className="demo-note">Задача, нотатка й розмова пов’язані в одному просторі.</p></div>}</div></div></>
}
export function App(){const [menu,setMenu]=useState(false),[layer,setLayer]=useState(0);return <><a className="skip" href="#main">Перейти до вмісту</a><header className="site-header wrap"><a className="wordmark" href="#" aria-label="VIDA — на початок">VIDA</a><nav aria-label="Головна навігація" className={menu?'open':''}>{navigation.map(([id,t])=><a href={'#'+id} key={id} onClick={()=>setMenu(false)}>{t}</a>)}</nav><span className="header-note">Простір для важливого</span><button className="mobile-menu" aria-label={menu?'Закрити меню':'Відкрити меню'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<List/>}</button></header>
 <main id="main"><section className="hero wrap editorial-hero" id="idea"><div className="hero-copy"><p className="status"><span/>VIDA — супер-ап у розробці</p><h1>Розмови, ідеї<br/>та справи —<br/>разом.</h1><p className="hero-description">VIDA пов’язує спілкування, знання та спільні плани. Долучайтеся до розробки локального застосунку зі спільним ядром Rust.</p><a className="button" href="#features">Дослідити можливості <ArrowRight/></a><a className="text-link developer-link" href="#join">Для розробників</a><div className="platforms" aria-label="Заплановані платформи">{[[AndroidLogo,'Android'],[AppleLogo,'iOS'],[WindowsLogo,'Windows'],[Globe,'Web']].map(([Icon,t])=><div key={t}><Icon size={30} weight={t==='Web'?'regular':'fill'}/><span>{t}</span></div>)}</div></div></section>
 <Problem/><section className="spaces wrap" aria-labelledby="space-title"><div className="section-heading"><h2 id="space-title">Особисте <ArrowRight/> Спільне</h2><p>Ви обираєте, чим ділитися.</p></div><div className="space-grid"><article className="space-card"><img src={import.meta.env.BASE_URL+"assets/personal-space.png"} alt="Людина працює у власному просторі" width="220" height="220"/><div><h3>Personal Space</h3><p className="space-lead">Ваші нотатки,<br/>розмови та плани.</p><p>Упорядковуйте ідеї, зберігайте важливе, плануйте свій день у власному просторі.</p></div></article><article className="space-card"><img src={import.meta.env.BASE_URL+"assets/shared-space.png"} alt="Команда працює разом" width="220" height="220"/><div><h3>Shared Space</h3><p className="space-lead">Спільна робота<br/>в обраному просторі.</p><p>Обговорюйте, плануйте, створюйте разом — у чатах, проєктах, файлах і дзвінках.</p></div></article></div><a href="#architecture" className="stack-strip"><Stack size={42}/><strong>Flutter · Rust · Iroh</strong><span>Спільне ядро, локальні дані, синхронізація між пристроями</span><div><DeviceMobile/><Desktop/><Laptop/></div><ArrowUpRight size={22}/></a></section>
 <section className="features wrap section" id="features"><div className="section-heading"><div><p className="eyebrow">МОЖЛИВОСТІ VIDA</p><h2>Важливе пов’язане.</h2></div><p>Заплановано для першого релізу.<br/>Один контекст замість розрізнених інструментів.</p></div><div className="feature-grid">{features.map(({icon:Icon,title,text,items},i)=><article key={title}><div className="feature-top"><Icon size={32}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p><ul>{items.map(t=><li key={t}><Check size={16}/>{t}</li>)}</ul></article>)}</div><div className="principles"><div><LockKey size={23}/><p><strong>Доступ за вашим вибором</strong><span>Окрема нотатка для контакту. Окремий Shared Space для команди.</span></p></div><div><Database size={23}/><p><strong>Корисно без зв’язку</strong><span>Локальний вміст доступний офлайн; доставка й синхронізація можуть чекати.</span></p></div><div><GitBranch size={23}/><p><strong>Контекст між застосунками</strong><span>Повідомлення, документ, задача та файл посилаються одне на одного.</span></p></div></div></section>
 <section className="apps section" id="apps"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">ЕКОСИСТЕМА ЗАСТОСУНКІВ</p><h2>Ваші задачі.<br/>Ваш набір застосунків.</h2></div><p>Спільні люди, дані й інструменти.<br/>Різні сценарії життя та роботи.</p></div><div className="app-grid">{applications.map(({icon:Icon,title,status,text,tags})=><article key={title}><div className="app-top"><Icon size={34}/><span className="tag">{status}</span></div><h3>{title}</h3><p>{text}</p><div className="app-tags">{tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div><p className="scope-note">Проєкти входять до погодженого першого релізу. CRM, ОСББ і запис до бізнесу — напрями розвитку екосистеми; склад функцій та строки ще потребують деталізації.</p></div></section>
 <section id="demo" className="demo-section section wrap"><div className="section-heading"><div><p className="eyebrow">ПРОТОТИП · ІНТЕРАКТИВНИЙ КОНЦЕПТ</p><h2>Розмова → нотатка → задача</h2></div><p>Три кроки в одному контексті.<br/>Без збереження даних і синхронізації.</p></div><div className="hero-demo"><WorkspaceDemo/></div></section><section className="architecture section" id="architecture"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">АРХІТЕКТУРА</p><h2>Різні пристрої.<br/>Спільна основа.</h2></div><p>Відкриті контракти й спільні правила<br/>для ядра, клієнтів та розширень.</p></div><div className="architecture-layout"><div className="layer-list" aria-label="Шари архітектури">{layers.map(({title,label,icon:Icon},i)=><button key={title} onClick={()=>setLayer(i)} aria-pressed={i===layer} className={i===layer?'selected':''}><span className="layer-number">0{i+1}</span><Icon size={25}/><strong>{title}</strong><span>{label}</span><ArrowUpRight size={20}/></button>)}</div><div className="layer-detail" aria-live="polite"><span className="eyebrow">{layers[layer].label}</span><h3>{layers[layer].title}</h3><p>{layers[layer].text}</p><div className="conformance"><ShieldCheck size={23}/><span>Сумісність перевірятиметься спільними специфікаціями та conformance-тестами.</span></div></div></div><a className="presentation-link" href="#technical-details">Відкрити технічний розбір і схеми ↗</a><p className="architecture-status">Заплановано. Архітектурні межі прийнято. Реалізація потребує перевірки прототипами: зокрема Web-з’єднання, спільний редактор і захищені дзвінки.</p></div></section>
 <ResearchGrowth/><ProjectState/><Contribution/>
 <section className="join" id="join"><div className="wrap join-layout"><div><p className="eyebrow">ВІДКРИТЕ ЗАПРОШЕННЯ</p><h2>Створімо VIDA разом</h2><p>Кращий простір для життя, ідей і спільних справ<br/>починається з людей, які хочуть його створити.</p></div><div><a className="button light" href={repo} target="_blank" rel="noreferrer">Долучитися до розробки <ArrowUpRight/></a><p className="join-caption">Публічний репозиторій · код і документація на GitHub</p><a className="presentation-link" href="https://docs.google.com/presentation/d/1DmRJqWwhgBMitWEkcKHw-hjjThPEYpoMSlGXy-HZ8f8/edit?usp=drivesdk" target="_blank" rel="noreferrer">Презентація на 5 хвилин · 9 слайдів ↗</a></div><div className="join-roles"><span>Rust та Flutter</span><span>UX і доступність</span><span>Тестування й безпека</span><span>Документація</span></div></div></section>
 <section id="technical-details" className="technical-intro"><div className="wrap"><p className="eyebrow">ТЕХНІЧНИЙ РОЗБІР</p><h2>Контракти, схеми та синхронізація.</h2><p className="narrative-lead">Нижче — цільова архітектура й відкриті реалізаційні рішення. Схеми пояснюють задум, а не підтверджують готовність продукту.</p><nav className="technical-nav" aria-label="Технічний розбір">{[['standard-apps','Стандартні можливості'],['composition','Бізнес-застосунки'],['marketplaces','Маркетплейси'],['external-platforms','Зовнішні платформи'],['infrastructure','Інфраструктура'],['iroh-protocol','Iroh'],['core-details','Ядро'],['schema-details','Схеми'],['sync-details','Синхронізація']].map(([id,label])=><a key={id} href={'#'+id}>{label}</a>)}</nav></div></section><StandardApps/><AppComposition/><Ecosystem/><IrohDetails/><ImplementationDetails/> </main><footer className="wrap footer"><a className="wordmark" href="#">VIDA</a><p>Простір для важливого.</p><span>Проєкт у розробці</span><a href={repo} target="_blank" rel="noreferrer" aria-label="VIDA на GitHub"><GithubLogo size={25}/></a></footer></>}
